[build]
  base = "client"
  publish = "client/dist"
  command = "cd client && npm run build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "cd client && npm run dev"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
